
[default]
ident = "WCPC"

[default.databases.sqlite_db]
url = "./database.sqlite"

[default.oauth.github]
provider = "GitHub"
redirect_uri = "http://localhost:8000/auth/callback/github"

[default.oauth.google]
provider = "Google"
redirect_uri = "http://localhost:8000/auth/callback/google"

[debug]
secret_key = "12345678901234567890123456789012345678901234"
template_dir = "frontend/dist"
