
name: CI

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
            - dev

concurrency:
    group: "ci-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    ci:
        name: CI
        strategy:
            fail-fast: false
            matrix:
              platform: [ubuntu-latest]
        permissions:
            contents: read
            id-token: write
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Cache Nix
              uses: DeterminateSystems/magic-nix-cache-action@main
            
            - name: Nix Check
              run: nix flake check
